### ISSUE TITLE
Strange CMake error

### ISSUE THREAD

**Issue by wilsonk** [Syniurge/Calypso#43] opened 2016-06-06 16:13 UTC
Hey Elie, I ran into this weird error with cmake, after yesterdays updates, when it tries to generate the ldc-druntime.dir/link.txt (and the -debug.dir/link file also). 

I was getting build errors where /bin/ar kept saying 'unrecognized file format' but that wasn't the real problem, the real problem was that the link.txt file had some stray backslashes in it like this:

```
/usr/bin/ar cr ../lib/libdruntime-ldc-debug.a  /home/wilsonk/Downloads/Calypso/build/runtime/_\
_cpp-__cxxabiv1-__base_class_type_info.o /home/wilsonk/Downloads/Calypso/build/runtime/__cpp-_\
_cxxabiv1-__class_type_info.o /home/wilsonk/Downloads/Calypso/build/runtime/\
__cpp-__cxxabiv1-__cxa_dependent_exception.o /home/wilsonk/Downloads/Calypso/build/runtime/__c\
pp-__cxxabiv1-__cxa_eh_globals.o /home/wilsonk/Downloads/Calypso/build/runtime/\
__cpp-__cxxabiv1-__cxa_exception.o /home/wilsonk/Downloads/Calypso/build/runtime/__cpp-__cxxab\
iv1-__cxa_refcounted_exception.o /home/wilsonk/Downloads/Calypso/build/runtime/\
__cpp-__cxxabiv1-_.o /home/wilsonk/Downloads/Calypso/build/runtime/__cpp-std-_.o /home/wilsonk\
/Downloads/Calypso/build/runtime/__cpp-std-type_info.o /home/wilsonk/Downloads/Calypso/build/r\
untime/__cpp-_Unwind_Action.o /home/wilsonk/Downloads/Calypso/build/runtime/\
__cpp-_Unwind_Context.o /home/wilsonk/Downloads/Calypso/build/runtime/__cpp-_Unwind_Exception.\
o /home/wilsonk/Downloads/Calypso/build/runtime/__cpp-_Unwind_Reason_Code.o CMakeFiles/druntim\
e-ldc-debug.dir/druntime/src/core/stdc/errno.c.o
```

 So it almost seems like there is a string copy that is failing after a certain length? Weird. I am using cmake-2.8.12.

**Comment by Syniurge** [comment] 2016-06-06 16:39
Hey Kelly,

They're supposed to break the long string literal into multiple lines, but I have CMake 3.3. Here's the string:

https://github.com/Syniurge/Calypso/blob/master/runtime/CMakeLists.txt#L139

I'll fix it tonight.
By the way I think that hack was pretty dumb since the list of files may depend a lot on the libstdc++ version... 

If you get a missing file error, trim down the list. The most important object files to prevent linking errors are:
- `__cpp-std-type_info.o`
- `__cpp-__cxxabiv1-_.o`
- `__cpp-__cxxabiv1-__cxa_exception.o`
- `__cpp-_Unwind_Exception.o`

**Comment by wilsonk** [comment] 2016-06-06 17:24
Hey Elie, yeah I just saw this commit 1232e3c, and I know what the line breaks are for...I just thought the line was automatically generated, so that maybe there was a character limit cmake was hitting or something. If I just remove the backslashes in that commit then things compile fine.

I am getting these errors in several places (like some of the libstdc++ tests), after the last few commits:

```
/home/wilsonk/Downloads/Calypso/build/lib/libdruntime-ldc.a(__cpp-__cxxabiv1-_.o): In function `__cxxabiv1::__get_object_from_ue(_Unwind_Exception*)':
/home/wilsonk/Downloads/Calypso/runtime/druntime/src/ldc/eh/cpp/unwind-cxx.h:383: undefined reference to `__cxa_call_unexpected'
/home/wilsonk/Downloads/Calypso/build/lib/libdruntime-ldc.a(__cpp-__cxxabiv1-_.o):(.eh_frame+0xcb): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
```

**Comment by Syniurge** [comment] 2016-06-06 21:24
Ok so you have one or more files to add to that list to prevent linking errors and as I feared the list won't be the same for older libstdc++ versions. Needs a better way..

**Comment by Syniurge** [comment] 2016-06-07 00:40
It should be fixed now with the new trick, can you confirm?

**Comment by wilsonk** [comment] 2016-06-07 01:07
The building is fixed but the undefined references are still there

**Comment by Syniurge** [comment] 2016-06-07 01:30
Actually those symbols are defined in libstdc++, are you passing -L-lsdc++ to LDC?

**Comment by wilsonk** [comment] 2016-06-07 01:46
I haven't changed the test runner in tests/libstdc++, so if -L-lstdc++ was being passed before then it still is...that is kind of the point, nothing changed here except moving to clang3.8 and the last few changes that were made to Calypso and now things don't work? Not sure why?

This is the error from the gdal example:

```
/usr/bin/ld: /home/wilsonk/Downloads/Calypso/build/lib/libdruntime-ldc.a(__cpp_monolith.o): undefined reference to symbol '_ZN10__cxxabiv117__class_type_infoD1Ev@@CXXABI_1.3'
/usr/lib/gcc/x86_64-linux-gnu/4.8/libstdc++.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

Does gdal compile and run for you?

**Comment by Syniurge** [comment] 2016-06-07 23:11
You're right, about every example compiles here but not the GDAL example, I get the same error. This is due to libstdc++ being before druntime in the linker call: `-lstdc++ -lphobos2-ldc -ldruntime-ldc`

Not sure why this one in particular failed to link and not the others.

Are there other examples that aren't working for you?

**Comment by Syniurge** [comment] 2016-06-08 01:16
The GDAL example is fixed, any linking error left for other examples?

**Comment by wilsonk** [comment] 2016-06-08 03:34
Seems like things are fine now. Just a quick question though...did something get changed that would affect compile times significantly? Things are orders of magnitude slower here!!! Seems to be a large pause when starting semantics on the qt demo and then each file takes quite a while to compile also...not sure what is going on. I didn't compile in debug mode.

**Comment by Syniurge** [comment] 2016-06-08 16:05
For me it's taking roughly the same time than it did before, I don't have the measurements with me but Calypso is currently slightly faster than it was with Clang 3.6. Some recent commits should have improved things:
- df1140a474a0b7e3a60c634eeb8312355e060b01 slightly reduces codegen time
- 648a62f15a2b9db98e077bc930ad34c2370f8fbe very slightly reduces codegen time (not verified)
- 95012c782909f538b0a42944b1af3c3098d35f54 cut down by 1/3 to 1/2 the time spent in the semantic pass but only once the PCH was generated (so only during the second compilation if the modmap'd headers weren't modified)

However compilation time is still a major issue. It has always been for me, at least. The Qt 5 demo takes ~13 mins to build the first time on my AMD A10-5750M, then 2m20s on subsequent compilations (once the PCH and the __cpp object files were generated).

The root cause of the long codegen times is the fragmentation of __cpp modules. For every module LDC/Clang have to recreate type and debug info metadata, redeclare used functions, etc. It would be multiple times faster to generate a larger __cpp module, which I'll consider at some point.

For the semantic pass during the first compilation what takes the most time is the instantiation of implicit methods (implicit constructors, copy assignment operators, etc. for each class/struct) and templates (because while Clang instantiates lazily, DMD instantiates much more). But those are now saved in the PCH, so the next run is much shorter.

This said, I don't know why it would be slower for you. How much time does it take to build the Qt 5 demo in release mode (which you can measure with `date` in bash)?

**Comment by wilsonk** [comment] 2016-06-08 20:35
Yeah, I saw those commits and thought that compilation times should improve (and they seemed to be a little better a week or so back), but now things seem slower. This is just a feeling I have, and not tested, as I don't have timings from a couple weeks back. Maybe it isn't as extreme as I thought and I am conflating the initial compile times with the second compilation times after the PCH generation.  This is not a huge deal, I just thought I would mention it to see if you were experiencing something similar.

Compilation times here in a VBox Linux VM on Win7 with an i5-4690 are 10m57s for Qt5demo and 0m57s for the recompilation after one change.

**Comment by Syniurge** [comment] 2016-06-20 16:25
Hey Kelly, so if everything went back to normal and stayed that way it may be time to close.

Btw thanks to b2c75369303a1b52e8a2217b2235c8d052adb94b, deleting __cpp*.o files manually to fix linking errors should never be needed anymore since now template instantiations get emitted in the right module.

**Closed as completed by Syniurge** 2016-06-20 16:25 UTC
